#ifndef _CONFIG_H_
#define _CONFIG_H_

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 400

#define LEFT_BAR_WIDTH 100

#define MANUAL_BUTTON_GAP 10
#define MANUAL_BUTTON_SIZE (LEFT_BAR_WIDTH-MANUAL_BUTTON_GAP*2)
#define MANUAL_BUTTON_Y 40
#define MANUAL_BUTTON_X MANUAL_BUTTON_GAP


#endif
