#ifndef _TOWER_H_
#define _TOWER_H_

#include "./config.h"

// Vertical
#define TOWER_LEVELS 2

// Horizontal
#define TOWER_STAGES 1

#define TOWER_BUTTON_GAP 5

#define TOWER_BUTTON_TOTAL_WIDTH ((SREEN_WIDTH-LEFT_BAR_WIDTH)/TOWER_STAGES)
#define TOWER_BUTTON_TOTAL_HEIGHT ((SREEN_HEIGHT-TOWER_BUTTON_GAP)/TOWER_LEVELS)

#define TOWER_BUTTON_WIDTH (TOWER_BUTTON_TOTAL_WIDTH-TOWER_BUTTON_GAP)
#define TOWER_BUTTON_HEIGHT (TOWER_BUTTON_TOTAL_HEIGHT-TOWER_BUTTON_GAP)

#define TOWER_BUTTON_START_X(level) (LEFT_BAR_WIDTH + TOWER_BUTTON_TOTAL_WIDTH*level)
#define TOWER_BUTTON_START_Y(stage) (TOWER_BUTTON_GAP + TOWER_BUTTON_TOTAL_HEIGHT*stage)

typedef struct TowerMatrix {
	unsigned int amounts[TOWER_LEVELS][TOWER_STAGES];
} TowerMatrix;

#endif
